MvcLiteBlog/Controllers/ArchiveController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ArchiveController.cs" company="LiteBlog">
//   Copyright (c) 2012, LiteBlog. All Rights Reserved.
// </copyright>
// <summary>
//   The archive controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace MvcLiteBlog.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using LiteBlog.Common;

    using MvcLiteBlog.BlogEngine;
    using MvcLiteBlog.Models;

    /// <summary>
    /// The archive controller.
    /// </summary>
    public class ArchiveController : Controller
    {
        #region Public Methods and Operators

        /// <summary>
        /// The archive.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Archive()
        {
            List<PostInfo> posts = BlogComp.GetPosts();
            IEnumerable<IGrouping<int, IGrouping<MonthYear, PostInfo>>> model =
                posts.GroupBy(p => new MonthYear { Month = p.Month, Year = p.Year }, new MonthYearComparer()).GroupBy(
                    group => group.Key.Year);

            return this.View(model);
        }

        /// <summary>
        /// The index.
        /// </summary>
        /// <param name="year">
        /// The year.
        /// </param>
        /// <param name="month">
        /// The month.
        /// </param>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Index(int year, int month)
        {
            string name = ArchiveComp.GetMonthName(month, year);
            if (name == string.Empty)
            {
                ArchiveMonth defMonth = ArchiveComp.GetDefaultMonth();
                year = defMonth.Year;
                month = defMonth.Month;
                name = defMonth.Name;
            }

            List<PostInfo> posts = BlogComp.GetPostsByMonth(year, month);
            this.ViewData.Model = posts;
            this.ViewData["ArchiveName"] = name;
            this.ViewBag.Year = year;
            return this.View();
        }

        /// <summary>
        /// The recent posts tile.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult RecentPostsTile()
        {
            List<PostInfo> posts = BlogComp.GetPosts();
            this.ViewData.Model = posts.Take(3);
            return this.PartialView();
        }

        /// <summary>
        /// The widget.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Widget()
        {
            List<ArchiveMonth> archMonths = ArchiveComp.GetArchiveMonths();
            IEnumerable<IGrouping<int, ArchiveMonth>> model = archMonths.GroupBy(m => m.Year);
            return this.PartialView("ArchiveControl", model);
        }

        #endregion
    }
}

MvcLiteBlog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Web.Mvc;
using System.Web.Routing;
using System.Xml;

using LiteBlog.Common;

using MvcLiteBlog.BlogEngine;
using MvcLiteBlog.Helpers;
using MvcLiteBlog.Models;

namespace MvcLiteBlog.Controllers
{
    public class BlogController : Controller
    {
        #region Public Methods and Operators

        /// <summary>
        /// The about.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult About()
        {
            return this.View();
        }

        /// <summary>
        /// The admin menu.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult AdminMenu()
        {
            return this.PartialView("AdminMenuControl");
        }

        /// <summary>
        /// The admin title.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult AdminTitle()
        {
            var model = PageComp.GetPublishedPages();
            Settings app = SettingsComp.GetSettings();
            this.ViewData["Title"] = app.Name;
            this.ViewData["IsAuthenticated"] = this.User.Identity.IsAuthenticated;
            this.ViewData["UserName"] = this.User.Identity.IsAuthenticated ? this.User.Identity.Name : string.Empty;
            return this.PartialView("AdminTitleControl", model);
        }

        /// <summary>
        /// The Atom
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Atom()
        {
            if (CacheHelper.Get<AtomBool>(CacheType.Atom) == null)
            {
                this.WriteFeedXml(FeedType.ATOM);
                AtomBool atom = new AtomBool(); // hack to use cache
                CacheHelper.Put(CacheType.Atom, atom);
            }

            StatComp.IncrementFeeds();

            ContentResult cr = new ContentResult();
            cr.ContentType = "application/atom+xml";

            StreamReader sr = new StreamReader(this.Server.MapPath("~/App_Data/Atom.xml"));
            cr.Content = sr.ReadToEnd();

            return cr;
        }

        /// <summary>
        /// The error.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Error()
        {
            return this.View();
        }

        /// <summary>
        /// The index.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        [HttpGet]
        public ActionResult Index()
        {
            this.ViewData.Model = BlogComp.GetDefaultPosts();
            return this.View();
        }

        /// <summary>
        /// The most popular tile.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult MostPopularTile()
        {
            Stat stat = this.ControllerContext.HttpContext.Application["Stat"] as Stat;
            return this.PartialView(stat.PageVisits.Take(10));
        }

        /// <summary>
        /// The rss.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Rss()
        {
            if (CacheHelper.Get<RssBool>(CacheType.Rss) == null)
            {
                this.WriteFeedXml(FeedType.RSS);
                RssBool rss = new RssBool(); // hack to use cache
                CacheHelper.Put(CacheType.Rss, rss);
            }

            StatComp.IncrementFeeds();

            ContentResult cr = new ContentResult();
            cr.ContentType = "application/rss+xml";

            StreamReader sr = new StreamReader(this.Server.MapPath("~/App_Data/rss.xml"));
            cr.Content = sr.ReadToEnd();

            return cr;
        }

        /// <summary>
        /// The stat.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Stat()
        {
            // Increment monthly visitors
            ProfileComp.SetVisitorProfile();

            // Increment hits of the page
            StatComp.IncrementHits();

            Stat stat = System.Web.HttpContext.Current.Application["Stat"] as Stat;
            this.ViewData.Model = stat;
            return this.PartialView("StatControl");
        }

        /// <summary>
        /// The title.
        /// </summary>
        /// <returns>
        /// The System.Web.Mvc.ActionResult.
        /// </returns>
        public ActionResult Title()
        {
            Settings app = SettingsComp.GetSettings();
            var model = PageComp.GetPublishedPages();
            this.ViewData["Title"] = app.Name;
            return this.PartialView("TitleControl", model);
        }

        #endregion

        #region Methods

        /// <summary>
        /// The initialize.
        /// </summary>
        /// <param name="requestContext">
        /// The request context.
        /// </param>
        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
        }

        /// <summary>
        /// The write feed xml.
        /// </summary>
        /// <param name="feedType">
        /// The feed Type.
        /// </param>
        private void WriteFeedXml(FeedType feedType)
        {
            Settings app = SettingsComp.GetSettings();
            string url = app.Url;
            if (url == string.Empty)
            {
                Uri uri = System.Web.HttpContext.Current.Request.Url;
                string dnsPath = uri.Scheme + "://" + uri.Host;
                if (!uri.IsDefaultPort)
                {
                    dnsPath = dnsPath + ":" + uri.Port.ToString();
                }

                string appPath = System.Web.HttpContext.Current.Request.ApplicationPath;
                url = dnsPath + appPath;
            }

            if (url.Substring(url.Length - 1, 1) != "/")
            {
                url += "/";
            }

            List<PostInfo> posts = BlogComp.GetPosts();
            List<SyndicationItem> items = new List<SyndicationItem>();

            int count = 0;
            foreach (PostInfo post in posts)
            {
                if (++count > 20)
                {
                    break;
                }

                SyndicationItem item = new SyndicationItem();
                item.Title = SyndicationContent.CreatePlaintextContent(post.Title);

                TimeSpan ts = DateTime.UtcNow - DateTime.Now;
                item.PublishDate = new DateTimeOffset(post.Time, ts);

                string url2 = string.Format("{0}Post/{1}", url, post.FileID);
                SyndicationLink link = SyndicationLink.CreateAlternateLink(new Uri(url2));

                item.Links.Add(link);

                Post post2 = PostComp.GetPost(post.FileID);
                item.Content = SyndicationContent.CreateHtmlContent(post2.Contents);

                string catName = CategoryComp.GetCategoryName(post.CatID);
                item.Categories.Add(new SyndicationCategory(catName));

                items.Add(item);
            }

            SyndicationFeed feed = new SyndicationFeed(items);

            feed.Title = SyndicationContent.CreatePlaintextContent(app.Name);
            feed.Links.Add(SyndicationLink.CreateAlternateLink(new Uri(url)));

            List<Author> authors = AuthorComp.GetAuthors();
            foreach (Author author in authors)
            {
                feed.Authors.Add(new SyndicationPerson(author.Email, author.Name, author.Url));
            }

            List<Category> catList = CategoryComp.GetCategories();
            foreach (Category cat in catList)
            {
                feed.Categories.Add(new SyndicationCategory(cat.Name));
            }

            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Encoding = System.Text.Encoding.UTF8;
            settings.OmitXmlDeclaration = true;
            settings.Indent = true;

            if (feedType == FeedType.RSS)
            {
                XmlWriter writer = XmlWriter.Create(this.Server.MapPath("~/App_Data/Rss.xml"), settings);
                feed.SaveAsRss20(writer);
                writer.Flush();
                writer.Close();
            }
            else
            {
                XmlWriter writer = XmlWriter.Create(this.Server.MapPath("~/App_Data/Atom.xml"), settings);
                feed.SaveAsAtom10(writer);
                writer.Flush();
                writer.Close();
            }
        }

        #endregion
    }
}

MvcLiteBlog/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LiteBlog.Common;
using MvcLiteBlog.Attributes;
using MvcLiteBlog.BlogEngine;
using MvcLiteBlog.Models;

namespace MvcLiteBlog.Controllers
{
    public class PageController : Controller
    {
        //
        // GET: /Page/

        public ActionResult Index(string id)
        {
            Page page = PageComp.Load(id);
            return View(page);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Manage()
        {
            var model = PageComp.GetPages();
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Compose(string id)
        {
            string fileId = id;
            Page page = new Page();
            if (!string.IsNullOrEmpty(fileId))
            {
                page = PageComp.Load(fileId);
            }

            var model = new ComposePageModel
            {
                FileId = page.FileId,
                Title = page.Title,
                Contents = page.Body
            };

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Delete(string id)
        {
            PageComp.Delete(id);
            TempData["Message"] = "页面已删除";
            return RedirectToAction("Manage");
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize]
        public ActionResult Save(ComposePageModel pageModel)
        {
            Page page = new Page
            {
                FileId = pageModel.FileId,
                Title = pageModel.Title,
                Body = pageModel.Contents
            };

            

            // Ajax call, return Json message
            if (string.IsNullOrEmpty(page.FileId))
            {
                // unique stuff.
                page.FileId = Guid.NewGuid().ToString();
            }

            page.Body = page.Body ?? string.Empty;

            PageComp.Save(page);

            DateTime now =
                LocalTime.GetCurrentTime(TimeZoneInfo.FindSystemTimeZoneById(SettingsComp.GetSettings().Timezone));
            
            StringWriter sw = new StringWriter();
            IView view = new RazorView(this.ControllerContext, "~/Views/Shared/AutoSaveControl.cshtml", null, false, null);
            this.ViewData.Model = now;
            ViewContext viewContext = new ViewContext(this.ControllerContext, view, this.ViewData, this.TempData, sw);
            view.Render(viewContext, sw);
            
            // PartialViewResult result = RenderViewToString this.PartialView("AutoSaveControl", now);
            return Json(new SavePageResultModel { FileId = page.FileId, Content = sw.ToString() });
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize]
        [MultiButton(FormName = "Publish", FormValue = "发布")]
        public ActionResult Publish(ComposePageModel pageModel)
        {
            // return if invalid model
            if (!ModelState.IsValid)
                return View(pageModel);

            Page page = new Page
            {
                FileId = pageModel.FileId,
                Title = pageModel.Title,
                Body = pageModel.Contents
            };

            // Save the new page
            PageComp.Publish(page);

            TempData["Message"] = "页面已发布";
            return this.RedirectToAction("Manage");
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize]
        [MultiButton(FormName = "Close", FormValue = "关闭")]
        public ActionResult Close(Page page)
        {
            return this.RedirectToAction("Manage");
        }

    }
}

MvcLiteBlog/Views/Shared/AdControl.cshtml
<div class="widget">
    <div class="widgetTitle">
        广告
    </div>
    <div style="margin: 5px auto; padding-bottom: 15px; text-align: center;">
        <script type="text/javascript"><!--
            google_ad_client = "ca-pub-9120781401397419";
            /* Tile Ad */
            google_ad_slot = "0606616694";
            google_ad_width = 200;
            google_ad_height = 200;
        //-->
        </script>
        <script type="text/javascript"
                src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
    </div>
</div>

MvcLiteBlog/Views/Shared/AdminTitleControl.cshtml
@model List<LiteBlog.Common.Page>
<div id="headerTitle">
    @this.Html.Raw((string)this.ViewData["Title"])
</div>
<div id="headerMenu">
    <ul>
        <li>@this.Html.ActionLink("首页", "Index", "Blog") </li>
        <li>@this.Html.ActionLink("管理", "Index", "Admin") </li>
        @*<li>@this.Html.ActionLink("LiteBlog", "Index", "LiteBlog") </li>*@
        @foreach (var page in Model)
        {
            <li>@this.Html.ActionLink(page.Title, "Index", "Page", new { id = page.FileId }, null)</li>
        }
    </ul>
</div>
<div id="headerStrip">
    @{
        var loginString = (bool)this.ViewData["IsAuthenticated"] ? "退出" : "登录";
        var loginAction = (bool)this.ViewData["IsAuthenticated"] ? "Logout" : "Index";

    }
    <span>@this.ViewData["UserName"]</span>
    &nbsp;&nbsp;&nbsp;&nbsp;
    @this.Html.ActionLink(loginString, loginAction, "Admin", null, new { @class = "LoginLink" })
</div>

MvcLiteBlog/Views/Shared/ArchiveControl.cshtml
@model IEnumerable<IGrouping<int, ArchiveMonth>>
<div class="widget">
    <div class="widgetTitle">
        存档
    </div>

    <ul id="archiveTree">
        @{
            foreach (IGrouping<int, ArchiveMonth> group in Model)
            {
            <li>@group.Key
                <ul>
                    @foreach (ArchiveMonth month in group)
                    {
                        <li>@this.Html.ActionLink(string.Format("{0} ({1})", month.Name, month.Count), "Index", "Archive", new { year = month.Year, month = month.Month }, null)</li>
                    }
                </ul>
            </li>        
            }
        }
        </ul>
        <div class="widgetBottom">
            @this.Html.ActionLink("存档", "Archive", "Archive")  | <img src="/Content/le-frog/images/rss_icon.png" style="margin-bottom:-2px;" /> @this.Html.ActionLink("RSS", "Rss", "Blog") | <img src="/Content/le-frog/images/atom_icon.png" style="margin-bottom:-2px;" /> @this.Html.ActionLink("ATOM", "Atom", "Blog")
        </div>


        <script type="text/javascript">
            $(document).ready(
                function () {
                    if (window.year==undefined) {
                        $('#archiveTree').simpletree({
                            expandAll: false,
                            expandFirstItem: true,
                            expandItem: ''
                        });
                    }
                    else {
                        $('#archiveTree').simpletree({
                            expandAll: false,
                            expandFirstItem: false,
                            expandItem: year
                        });
                    }
                });
        </script>
   
</div>

MvcLiteBlog/Views/Shared/AutoSaveControl.cshtml
@model DateTime

<span style="color: blue; font-size: 0.8em;">这篇文章已在 @this.Model.ToString("hh:mm:ss tt") 时自动保存。</span>

MvcLiteBlog/Views/Shared/CategoryControl.cshtml
@model List<Category>

<div class="widget">
    <div class="widgetTitle">
        分类
    </div>
    <ul class="widgetList">
        @foreach (Category cat in this.Model)
        {
            <li>
                @this.Html.ActionLink(string.Format("{0} ({1})", cat.Name, cat.Count), "Index", "Category", new { id = cat.CatID }, null)
            </li>
        }
    </ul>
</div>

MvcLiteBlog/Views/Shared/CommentControl.cshtml
@model List<Comment>
         
<div id="commentCounts">
    @if(@Model.Count == 0){
        <span>无评论</span>
    }
    else{
        <span>@Model.Count() 条评论</span>
    }
</div>          
@foreach (Comment comment in this.Model)
{
    if (comment.IsAuthor)
    {
        <div class="authorBg">
            <div class="commentImage commentContent">
                <img src="@Url.Content("~/Content/le-frog/images/commentImage.jpg")" />
            </div>
            <div class="commentHeader">
                <a name="@comment.ID"></a>
                @if (comment.Url == string.Empty)
                {
                    @comment.Name
                }
                else
                {
                    <a href="@comment.Url" target="_blank">@comment.Name</a>
                }
                <span class="muted"> 于 @comment.Time.ToString(MvcLiteBlog.Helpers.ConfigHelper.DateFormat, System.Globalization.CultureInfo.InvariantCulture) 评论</span>
            </div>
            <div class="comment">
                @this.Html.Raw(comment.HighlightedCode)
            </div>
        </div>
    }
    else
    {
        <div class="commentContent">
            <div class="commentImage">
                <img src="@Url.Content("~/Content/le-frog/images/commentImage.jpg")" />
            </div>
            <div class="commentHeader">
                <a name="@comment.ID"></a>
                @if (comment.Url == string.Empty)
                {
                    @comment.Name
                }
                else
                {
                    <a href="@comment.Url" target="_blank">@comment.Name</a>
                }
                <span class="muted"> 于 @comment.Time.ToString(MvcLiteBlog.Helpers.ConfigHelper.DateFormat, System.Globalization.CultureInfo.InvariantCulture) 评论</span>
            </div>
            <div class="comment">
                @this.Html.Raw(comment.HighlightedCode)
            </div>
        </div>
    }
}
 



MvcLiteBlog/Views/Shared/CommentFormControl.cshtml
@model MvcLiteBlog.Models.InsertCommentModel
           
@using (this.Html.BeginForm("Create", "Comment"))
{
    <div class="ModalWindow">
        <fieldset>
            <legend>添加评论</legend>
            <div class="">
                <span id="commentResult"></span>
                @*<input type="hidden" name="FileID" id="_hdnFileID" />*@
                @this.Html.HiddenFor(m => m.FileID, new { id = "_hdnFileID" })
                @this.Html.HiddenFor(m => m.IsAuthor)
            </div>
            <div class="editor_label">
                <label for="Name">称呼：</label>
            </div>
            <div class="editor_field">
                @this.Html.TextBoxFor(m => m.Name, new { placeholder = "您的称呼" })
            </div>
            <div class="editor_label">
                <label for="Url">博客地址：</label>
            </div>
            <div class="editor_field">
                @this.Html.TextBoxFor(m => m.Url, new { placeholder = "您博客的地址" })
           
            </div>
            <div class="editor_label">
                <label for="CommentText">评论内容：</label>
            </div>
            <div class="editor_field">
                <textarea id="commentEditor" name="CommentText" rows="10" cols="30" placeholder="请填写您的评论"></textarea>
            </div>
            <div class="button">
                <a href="#" id="addCommentLink">发表评论</a>
            </div>
        </fieldset>
    </div>
}


 

MvcLiteBlog/Views/Shared/LogOnUserControl.cshtml
@if (this.Request.IsAuthenticated)
{
    <span>欢迎 <b>@this.Page.User.Identity.Name</b>!
        [ @this.Html.ActionLink("Log Off", "LogOff", "Account") ]</span>
}
else
{
    <span>[ @this.Html.ActionLink("Log On", "LogOn", "Account") ]</span>
}

MvcLiteBlog/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <title>@this.ViewBag.Title</title>
        <meta name="keywords" content="皮卡,皮卡工作室,Pickup,Pickup Studio,RememberIt,Kinver,zdybit,LPraYer,宽厚,逢冬飘雪" />
        <meta name="description" content="皮卡工作室关注和收集泛互联网行业的前沿动态，并将新鲜的想法转化为产品。" />
        <!--基本兼容ie8以上浏览器，使用可选的最高的ie渲染模式-->
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" >
        <link rel="icon" type="image/x-icon" href="~/Content/le-frog/images/favicon.ico" />
        <link rel="shortcut icon" type="image/x-icon" href="~/Content/le-frog/images/favicon.ico" />
        <link href="@this.Url.Content("~/Content/le-frog/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
        <link href="@this.Url.Content("~/Content/Admin.css")" rel="stylesheet" type="text/css" />
        <link href="@this.Url.Content("~/Content/bootstrap.css") rel="stylesheet" type="text/css" />
        <script src='@this.Url.Content("~/Scripts/MicrosoftAjax.debug.js")' type="text/javascript"></script>
        <script src='@this.Url.Content("~/Scripts/MicrosoftMvcAjax.debug.js")' type="text/javascript"></script>
        <script src='@this.Url.Content("~/Scripts/MicrosoftMvcValidation.debug.js")' type="text/javascript"></script>
        <script src='@this.Url.Content("~/Scripts/jquery-1.6.2.min.js")' type="text/javascript"></script>
        <script src='@this.Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")' type="text/javascript"></script>
        <script type="text/javascript">
            var appPath = '@this.Url.Content("~/")';

            $(document).ready(
                function() {
                    $('input[type=submit], input[type=button], a', '.button, .leftButton').button();
                });

        </script>
        @this.RenderSection("ScriptSection", false)
    </head>
    <body>
        <div class="page">
            <div id="header">
                @this.Html.Action("AdminTitle", "Blog")
            </div>
            <div id="middle">
                <div id="left">
                    @{ this.Html.RenderAction("AdminMenu", "Blog"); }
                </div>
                <div id="center">
                    @{ this.Html.EnableClientValidation(); }

                    @this.RenderBody()
                </div>
                <div style="clear: both;">&nbsp;</div>
            </div>
       
            <div id="footer">
                &copy; 2012 皮卡网志
            </div>
        </div>
    </body>
</html>

MvcLiteBlog/Views/Shared/_SiteLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@this.ViewBag.Title</title>
    <meta name="keywords" content="皮卡,皮卡工作室,Pickup,Pickup Studio,RememberIt,Kinver,zdybit,LPraYer,宽厚,逢冬飘雪" />
    <meta name="description" content="皮卡工作室关注和收集泛互联网行业的前沿动态，并将新鲜的想法转化为产品。" />
    <!--基本兼容ie8以上浏览器，使用可选的最高的ie渲染模式-->
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" >
    <link rel="icon" type="image/x-icon" href="~/Content/le-frog/images/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/le-frog/images/favicon.ico" />
    <link href="@this.Url.Content("~/Content/Blog.css")" rel="stylesheet" type="text/css" />
    <link href="@this.Url.Content("~/Content/le-frog/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@this.Url.Content("~/Content/SimpleTree.css")" rel="stylesheet" type="text/css" />
    <style type="text/css">
        /*ie6提示*/
        #ie6-warning{width:100%;position:absolute;top:0;left:0;z-index:1031;background:#f5ff00;padding:10px 0;font-size:12px;}
        #ie6-warning p{width:100%;margin:0 auto;text-align:center;}
    </style>
    <script src='@this.Url.Content("~/Scripts/MicrosoftAjax.debug.js")' type="text/javascript"></script>
    <script src='@this.Url.Content("~/Scripts/MicrosoftMvcAjax.debug.js")' type="text/javascript"></script>
    <script src='@this.Url.Content("~/Scripts/jquery-1.6.2.min.js")' type="text/javascript"></script>
    <script src='@this.Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")' type="text/javascript"></script>
    <script src="@this.Url.Content("~/Scripts/Custom/plugins/simpletree.js")" type="text/javascript"></script>
    <script type="text/javascript">
        var appPath = '@this.Url.Content("~/")';
    </script>
    @this.RenderSection("ScriptSection", false)
</head>
<body>
    <div class="page">
        <!--[if lte IE 6]>
        <div id="ie6-warning">
            <p>
                我们已不再支持 Internet Explorer 6 。建议您升级到
                <a href="http://www.microsoft.com/china/windows/internet-explorer/" target="_blank">
                更高版本</a>
                或选用以下现代浏览器：
                <a href="http://www.google.com/chrome/?hl=zh-CN">Chrome</a> / <a href="http://www.mozillaonline.com/">Firefox</a> / <a href="http://www.apple.com.cn/safari/">Safari</a> / <a href="http://www.operachina.com/">Opera</a>
            </p>
        </div>
        <![endif]-->
        <div id="header">
            @this.Html.Action("Title", "Blog")
        </div>
        <div id="middle">
            <div id="center">
                @this.RenderBody()
            </div>
            <div id="right">
                @this.Html.Action("MostPopularTile", "Blog")
                @this.Html.Action("RecentCommentsTile", "Comment")
                @this.Html.Action("Widget", "Category")
                @this.Html.Action("Widget", "Archive")
                @this.Html.Action("Stat", "Blog")
                @this.Html.Partial("AdControl")
            </div>
            <div style="clear: both;">&nbsp;</div>
        </div>
        <div id="footer">
            &copy; 2012 皮卡网志
        </div>
    </div>
    <script type="text/javascript">
        function setShare(title, url, summary) {
            jiathis_config.title = title;
            jiathis_config.url = url;
            jiathis_config.summary = summary;
        }
        var jiathis_config = {}
    </script>
    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1350656775435570" charset="utf-8"></script>
    <script type="text/javascript">
        var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
        document.write('<div style="display:none">' + unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Ff1c27a1f5e4ddd21285a8a21e0ba3f8e' type='text/javascript'%3E%3C/script%3E") + '</div>');
        //ie6 warning
        jQuery(function ($) {
            if (jQuery.browser.msie && (jQuery.browser.version == "6.0") && !jQuery.support.style) {
                jQuery('#ie6-warning').css({ 'top': jQuery(this).scrollTop() + 'px' });
            }
        });
    </script>
</body>
</html>